site_name: DocMigrator
site_url: https://timmoth.github.io/DocMigrator/
site_description: Ensures that documents are migrated before being used.
site_author: Timmoth
repo_url: https://github.com/Timmoth/DocMigrator/
edit_uri: edit/main/docs

theme:
  name: readthedocs
  highlightjs: true
  logo: assets/logo.png
  hljs_languages:
    - csharp
nav:
  - Overview âœ…: index.md
  - Releases ğŸ“’: releases.md
  - Support ğŸ›Ÿ: support.md
  - Contributing ğŸ™: contributing.md

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
